help:
	@printf "\n"
	@printf "VehicleRoutingProblem - Make Help\n"
	@printf "=================================\n\n"
	@printf "COMANDI ESEMPIO - LOCALE:\n"
	@printf "  make solve_pyvrp SOLVE_CLIENTS=500,1000,2000,4000,8000 SOLVE_PYVRP_RUNTIME_S=300 SOLVE_PYVRP_SEED=1234\n"
	@printf "  make solve_seq SOLVE_CLIENTS=500,1000,2000,4000,8000 SOLVE_SEQ_REPEATS=3 SOLVE_SEQ_RUNTIME_S=300 SOLVE_SEQ_STAGNATION_EPOCHS=80 SOLVE_SEQ_MIN_REL_IMPROVEMENT=10\n"
	@printf "  make solve_mpi SOLVE_CLIENTS=500,1000,2000,4000,8000 SOLVE_MPI_REPEATS=3 SOLVE_MPI_RUNTIME_S=300 SOLVE_MPI_STAGNATION_EPOCHS=80 SOLVE_MPI_MIN_REL_IMPROVEMENT=10 SOLVE_MPI_RANKS=4 SOLVE_MPI_OMP_THREADS=8\n"
	@printf "  make solve_cuda SOLVE_CLIENTS=500,1000,2000,4000,8000 SOLVE_CUDA_REPEATS=3 SOLVE_SEQ_RUNTIME_S=300 SOLVE_SEQ_STAGNATION_EPOCHS=80 SOLVE_SEQ_MIN_REL_IMPROVEMENT=10 SOLVE_CUDA_VARIANT=v6\n"
	@printf "  make solve_seq SOLVE_SEQ_REPEATS=3 SOLVE_SEQ_RUNTIME_S=300 SOLVE_SEQ_STAGNATION_EPOCHS=80 SOLVE_SEQ_MIN_REL_IMPROVEMENT=10\n"
	@printf "  make solve_seq && make solve_mpi && make solve_cuda\n\n"
	@printf "COMANDI ESEMPIO - CLUSTER (dentro job allocato):\n"
	@printf "  make solve_seq SOLVE_SEQ_REPEATS=3 SOLVE_SEQ_RUNTIME_S=300 SOLVE_SEQ_STAGNATION_EPOCHS=80 SOLVE_SEQ_MIN_REL_IMPROVEMENT=10\n"
	@printf "  make solve_mpi SOLVE_MPI_REPEATS=3 SOLVE_MPI_RUNTIME_S=300 SOLVE_MPI_STAGNATION_EPOCHS=80 SOLVE_MPI_MIN_REL_IMPROVEMENT=10 SOLVE_MPI_RANKS=$${SLURM_NTASKS:-4} SOLVE_MPI_OMP_THREADS=32 SOLVE_MPI_LAUNCHER=mpirun\n"
	@printf "  make solve_cuda SOLVE_CUDA_REPEATS=3 SOLVE_SEQ_RUNTIME_S=300 SOLVE_SEQ_STAGNATION_EPOCHS=80 SOLVE_SEQ_MIN_REL_IMPROVEMENT=10 SOLVE_CUDA_VARIANT=v6\n"
	@printf "  make generate_problems GEN_CLIENTS=4000,8000,16000,32000,64000,128000,200000\n"
	@printf "  make generate_problems_big\n"
	@printf "  make solve_pyvrp SOLVE_CLIENTS=500,1000 SOLVE_PYVRP_RUNTIME_S=300\n"
	@printf "  make solve_seq   SOLVE_CLIENTS=500,1000,2000 SOLVE_SEQ_RUNTIME_S=300 SOLVE_SEQ_STAGNATION_EPOCHS=80 SOLVE_SEQ_MIN_REL_IMPROVEMENT=10 SOLVE_SEQ_REPEATS=3\n"
	@printf "  make solve_cuda  SOLVE_CLIENTS=500,1000 SOLVE_CUDA_REPEATS=3 SOLVE_SEQ_RUNTIME_S=300 SOLVE_SEQ_STAGNATION_EPOCHS=80 SOLVE_SEQ_MIN_REL_IMPROVEMENT=10\n"
	@printf "  make solve_mpi   SOLVE_CLIENTS=4000,8000 SOLVE_MPI_RANKS=4 SOLVE_MPI_OMP_THREADS=8 SOLVE_MPI_RUNTIME_S=300 SOLVE_MPI_STAGNATION_EPOCHS=80 SOLVE_MPI_MIN_REL_IMPROVEMENT=10 SOLVE_MPI_REPEATS=3\n"
	@printf "  make solve_memory_growth_non_cuda SOLVE_MPI_RANKS=4 SOLVE_MPI_OMP_THREADS=8\n"
	@printf "  make exp_strong_openmp\n"
	@printf "  make exp_weak_openmp\n"
	@printf "  make exp_strong_mpi\n"
	@printf "  make exp_strong_hybrid\n"
	@printf "  make exp_weak_mpi\n"
	@printf "  make exp_weak_hybrid\n"
	@printf "  make exp_all\n"
	@printf "  make solve_all   SOLVE_CLIENTS=500,1000\n\n"
	@printf "TARGET GENERAZIONE PROBLEMI:\n"
	@printf "  %-42s | %s\n" "generate_problems" "Genera istanze .vrp + manifest.csv + manifest_openmp_mpi.csv"
	@printf "  %-42s | %s\n" "generate_problems_big" "Profilo istanze grandi non-CUDA (4k..32k)"
	@printf "  %-42s | %s\n\n" "generate_clean" "Rimuove istanze/manifest generati in GEN_INST_DIR"
	@printf "TARGET BUILD:\n"
	@printf "  %-42s | %s\n" "all" "Compila tutti i solver -> seq + MPI+OpenMP + CUDA"
	@printf "  %-42s | %s\n" "seq" "Compila solo il solver sequenziale -> aco_vrp_seq.out"
	@printf "  %-42s | %s\n" "openmp_mpi" "Compila il solver MPI+OpenMP -> aco_vrp_openmp_mpi.out"
	@printf "  %-42s | %s\n" "cuda" "Compila il solver CUDA -> aco_vrp_cuda.out"
	@printf "  %-42s | %s\n" "debug" "Ricompila con flag -DDEBUG"
	@printf "  %-42s | %s\n\n" "clean" "Pulisce binari, oggetti, coverage e artefatti CUDA intermedi"
	@printf "TARGET SOLVE DA MANIFEST (PRODUZIONE DATI):\n"
	@printf "  %-42s | %s\n" "solve_prepare" "Crea cartelle output e verifica esistenza manifest"
	@printf "  %-42s | %s\n" "solve_pyvrp" "Legge SOLVE_MANIFEST, risolve con PyVRP, salva CSV + route txt"
	@printf "  %-42s | %s\n" "solve_seq" "Legge SOLVE_MANIFEST, esegue solver sequenziale, salva CSV + route txt"
	@printf "  %-42s | %s\n" "solve_cuda" "Legge SOLVE_MANIFEST, esegue solver CUDA, salva CSV + route txt"
	@printf "  %-42s | %s\n" "solve_mpi" "Legge SOLVE_MANIFEST_MPI, esegue solver MPI, salva CSV + route txt"
	@printf "  %-42s | %s\n" "solve_memory_growth_non_cuda" "Esegue seq+mpi con ripetizioni e CSV con max_rss_gb"
	@printf "  %-42s | %s\n\n" "solve_all" "Esegue in sequenza: solve_pyvrp, solve_seq, solve_cuda, solve_mpi"
	@printf "TARGET ESPERIMENTI SCALING:\n"
	@printf "  %-42s | %s\n" "exp_strong_openmp" "Strong scaling OpenMP: N fisso, ranks=1, thread variabili"
	@printf "  %-42s | %s\n" "exp_weak_openmp" "Weak scaling OpenMP: coppie (threads,n) da EXP_WEAK_OPENMP_PAIRS"
	@printf "  %-42s | %s\n" "exp_strong_mpi" "Strong scaling MPI: N fisso, OMP fisso, ranks variabili"
	@printf "  %-42s | %s\n" "exp_strong_hybrid" "Strong scaling ibrido: N fisso, coppie (ranks,threads)"
	@printf "  %-42s | %s\n" "exp_weak_mpi" "Weak scaling MPI: coppie (ranks,n) da EXP_WEAK_MPI_PAIRS"
	@printf "  %-42s | %s\n" "exp_weak_hybrid" "Weak scaling ibrido: triple (ranks,threads,n) da EXP_WEAK_HYBRID_TRIPLETS"
	@printf "  %-42s | %s\n\n" "exp_all" "Esegue in sequenza: exp_strong_openmp, exp_weak_openmp, exp_strong_mpi, exp_strong_hybrid, exp_weak_mpi, exp_weak_hybrid"
	@printf "VARIABILI PER solve_*:\n"
	@printf "  %-60s | %s\n" "RESULTS_ROOT=results" "Root unica risultati (solve)"
	@printf "  %-60s | %s\n" "SOLVE_OUT_DIR=$(RESULTS_ROOT)/solve_manifest" "Directory base output solve_*"
	@printf "  %-60s | %s\n" "SOLVE_CSV_DIR=$(SOLVE_OUT_DIR)/csv" "Directory CSV solve_*"
	@printf "  %-60s | %s\n" "SOLVE_SOLUTIONS_DIR=$(SOLVE_OUT_DIR)/solutions" "Directory route per backend"
	@printf "  %-60s | %s\n" "SOLVE_MANIFEST=.../manifest.csv" "Manifest usato da solve_pyvrp/solve_seq/solve_cuda"
	@printf "  %-60s | %s\n" "SOLVE_MANIFEST_MPI=.../manifest_openmp_mpi.csv" "Manifest usato da solve_mpi"
	@printf "  %-60s | %s\n" "SOLVE_CLIENTS=500,1000,4000" "Filtra per numero clienti n (colonna 4 del manifest)"
	@printf "  %-60s | %s\n" "SOLVE_LIMIT=5" "Limita alle prime N righe dopo i filtri (0 = tutte)"
	@printf "  %-60s | %s\n" "SOLVE_PYVRP_RUNTIME_S=10" "Budget tempo per istanza PyVRP (secondi)"
	@printf "  %-60s | %s\n" "SOLVE_SEQ_RUNTIME_S=0" "Budget tempo seq (secondi, 0=disattivo)"
	@printf "  %-60s | %s\n" "SOLVE_SEQ_RUNTIME=60" "Alias compatibile di SOLVE_SEQ_RUNTIME_S"
	@printf "  %-60s | %s\n" "SOLVE_SEQ_STAGNATION_EPOCHS=0" "Stop seq dopo N epoche senza miglioramento relativo significativo (0=off)"
	@printf "  %-60s | %s\n" "SOLVE_SEQ_MIN_REL_IMPROVEMENT=0.1" "Percentuale minima di miglioramento relativo per epoca (0.1 = 0.1%%)"
	@printf "  %-60s | %s\n" "SOLVE_SEQ_M=0" "Override m (formiche) per solve_seq; 0=usa manifest"
	@printf "  %-60s | %s\n" "SOLVE_SEQ_REPEATS=1" "Ripetizioni per istanza nel solve_seq"
	@printf "  %-60s | %s\n" "SOLVE_MPI_RUNTIME_S=0" "Budget tempo per istanza MPI+OpenMP (secondi, 0=disattivo)"
	@printf "  %-60s | %s\n" "SOLVE_MPI_STAGNATION_EPOCHS=0" "Stop MPI dopo N epoche senza miglioramento relativo significativo (0=off)"
	@printf "  %-60s | %s\n" "SOLVE_MPI_MIN_REL_IMPROVEMENT=0.1" "Percentuale minima di miglioramento relativo per epoca MPI (0.1 = 0.1%%)"
	@printf "  %-60s | %s\n" "SOLVE_MPI_REPEATS=1" "Ripetizioni per istanza nel solve_mpi"
	@printf "  %-60s | %s\n" "SOLVE_PYVRP_SEED=1234" "Seed PyVRP"
	@printf "  %-60s | %s\n" "SOLVE_MPI_RANKS=2" "Numero processi MPI per solve_mpi"
	@printf "  %-60s | %s\n" "SOLVE_MPI_OMP_THREADS=2" "Thread OpenMP per rank MPI"
	@printf "  %-60s | %s\n" "SOLVE_MPI_LAUNCHER=auto" "Launcher MPI: auto|mpirun|srun"
	@printf "  %-60s | %s\n" "SOLVE_CUDA_IMPROVEMENT=0.001" "Soglia miglioramento early-stop CUDA"
	@printf "  %-60s | %s\n\n" "SOLVE_CUDA_REPEATS=1" "Ripetizioni per istanza nel solve_cuda"
	@printf "VARIABILI PER exp_*:\n"
	@printf "  %-60s | %s\n" "EXP_REPEATS=5" "Ripetizioni per ogni punto sperimentale"
	@printf "  %-60s | %s\n" "EXP_STAGNATION_EPOCHS=500" "Stop epoche senza miglioramento (usato in exp_*)"
	@printf "  %-60s | %s\n" "EXP_MIN_REL_IMPROVEMENT=0.001" "Soglia miglioramento relativo percentuale"
	@printf "  %-60s | %s\n" "EXP_MPI_LAUNCHER=mpirun" "Launcher MPI usato dai target exp_*"
	@printf "  %-60s | %s\n" "EXP_MAX_CLUSTER_NODES=4" "Numero massimo nodi MPI da usare negli auto-scaling"
	@printf "  %-60s | %s\n" "EXP_WEAK_BASE_N_PER_WORKER=2000" "Base N per worker usata nelle modalita auto weak"
	@printf "  %-60s | %s\n" "EXP_STRONG_OPENMP_N=2000" "N fisso per strong OpenMP"
	@printf "  %-60s | %s\n" "EXP_STRONG_OPENMP_THREADS=auto" "Thread OpenMP da testare (auto -> potenze di 2 fino ai core)"
	@printf "  %-60s | %s\n" "EXP_WEAK_OPENMP_PAIRS=auto" "Coppie threads N per weak OpenMP (auto -> N proporzionale ai thread)"
	@printf "  %-60s | %s\n" "EXP_STRONG_MPI_N=16000" "N fisso per strong MPI"
	@printf "  %-60s | %s\n" "EXP_STRONG_MPI_RANKS=auto" "Ranks MPI da testare (auto -> 1,2,4 fino a EXP_MAX_CLUSTER_NODES)"
	@printf "  %-60s | %s\n" "EXP_STRONG_MPI_OMP_THREADS=8" "OMP fisso per strong MPI"
	@printf "  %-60s | %s\n" "EXP_STRONG_HYBRID_N=16000" "N fisso per strong ibrido MPI+OpenMP"
	@printf "  %-60s | %s\n" "EXP_STRONG_HYBRID_PAIRS=auto" "Coppie rank thread per strong ibrido (auto -> r=t in potenze di 2)"
	@printf "  %-60s | %s\n" "EXP_WEAK_MPI_PAIRS=auto" "Coppie rank N per weak scaling (auto -> N proporzionale ai rank)"
	@printf "  %-60s | %s\n\n" "EXP_WEAK_MPI_OMP_THREADS=8" "OMP fisso per weak MPI"
	@printf "  %-60s | %s\n\n" "EXP_WEAK_HYBRID_TRIPLETS=auto" "Triple rank thread N per weak ibrido (auto -> N proporzionale a rank*thread)"
	@printf "VARIABILI GENERAZIONE:\n"
	@printf "  %-60s | %s\n" "GEN_INST_DIR=instances/test_aligned" "Directory dove scrivere .vrp e manifest"
	@printf "  %-60s | %s\n" "GEN_CLIENTS=4000,8000,16000,32000,64000,128000,200000" "Taglie n da generare (CSV separato da virgole)"
	@printf "  %-60s | %s\n" "GEN_SEED_BASE=19000" "Seed base; per ogni istanza incrementa di 1"
	@printf "  %-60s | %s\n" "GEN_GRID=100" "Griglia coordinate passata al generatore"
	@printf "  %-60s | %s\n" "GEN_SOLVER_SEED=1234" "Seed solver scritto nei manifest"
	@printf "  %-60s | %s\n" "GEN_TARGET_CUSTOMERS_PER_VEHICLE=1024" "Obiettivo medio clienti/veicolo: K = ceil(n / target)"
	@printf "  %-60s | %s\n" "GEN_MIN_VEHICLES=8" "Minimo veicoli generati"
	@printf "  %-60s | %s\n" "GEN_MAX_VEHICLES=512" "Massimo veicoli generati"
	@printf "  %-60s | %s\n" "GEN_CAPACITY_SLACK_PERCENT=20" "Slack percentuale sulla capacita: CAPACITY = ceil((1 + slack/100) * n / K)"
	@printf "  %-60s | %s\n\n" "Capacita generata" "Sempre ceil((1 + slack/100) * n / K) con domanda unitaria per cliente"
	@printf "OUTPUT GENERATI DA solve_*:\n"
	@printf "  %-85s | %s\n" "$(SOLVE_CSV_DIR)/manifest_pyvrp_per_instance_results.csv" "CSV PyVRP con elapsed, memoria (max_rss_gb), costo"
	@printf "  %-85s | %s\n" "$(SOLVE_CSV_DIR)/manifest_seq_per_instance_results.csv" "CSV solver sequenziale (con max_rss_gb)"
	@printf "  %-85s | %s\n" "$(SOLVE_CSV_DIR)/manifest_cuda_<variant>_per_instance_results.csv" "CSV solver CUDA"
	@printf "  %-85s | %s\n" "$(SOLVE_CSV_DIR)/manifest_openmp_mpi_per_instance_results.csv" "CSV solver MPI+OpenMP (con max_rss_gb)"
	@printf "  %-85s | %s\n\n" "$(SOLVE_SOLUTIONS_DIR)/<backend>/*.txt" "Route complete per ogni istanza/backend"
