help:
	@printf "\n"
	@printf "VehicleRoutingProblem - Make Help\n"
	@printf "=================================\n\n"
	@printf "COMANDI ESEMPIO - LOCALE:\n"
	@printf "  make solve_pyvrp SOLVE_CLIENTS=1000,2000,4000,8000 SOLVE_PYVRP_RUNTIME_S=300 SOLVE_PYVRP_SEED=1234\n"
	@printf "  make solve_seq SOLVE_CLIENTS=1000,2000,4000,8000 SOLVE_SEQ_REPEATS=3 SOLVE_SEQ_RUNTIME_S=300 SOLVE_SEQ_STAGNATION_EPOCHS=80 SOLVE_SEQ_MIN_REL_IMPROVEMENT=10\n"
	@printf "  make solve_mpi SOLVE_CLIENTS=1000,2000,4000,8000 SOLVE_MPI_REPEATS=3 SOLVE_MPI_RUNTIME_S=300 SOLVE_MPI_STAGNATION_EPOCHS=80 SOLVE_MPI_MIN_REL_IMPROVEMENT=10 SOLVE_MPI_RANKS=4 SOLVE_MPI_OMP_THREADS=8\n"
	@printf "  make solve_cuda SOLVE_CLIENTS=1000,2000,4000,8000 SOLVE_CUDA_REPEATS=3 SOLVE_CUDA_RUNTIME_S=300 SOLVE_CUDA_STAGNATION_EPOCHS=80 SOLVE_CUDA_MIN_REL_IMPROVEMENT=10\n"
	@printf "  make solve_seq SOLVE_SEQ_REPEATS=3 SOLVE_SEQ_RUNTIME_S=300 SOLVE_SEQ_STAGNATION_EPOCHS=80 SOLVE_SEQ_MIN_REL_IMPROVEMENT=10\n"
	@printf "  make solve_seq && make solve_mpi && make solve_cuda\n\n"
	@printf "COMANDI ESEMPIO - CLUSTER (dentro job allocato):\n"
	@printf "  make solve_seq SOLVE_SEQ_REPEATS=3 SOLVE_SEQ_RUNTIME_S=300 SOLVE_SEQ_STAGNATION_EPOCHS=80 SOLVE_SEQ_MIN_REL_IMPROVEMENT=10\n"
	@printf "  make solve_mpi SOLVE_MPI_REPEATS=3 SOLVE_MPI_RUNTIME_S=300 SOLVE_MPI_STAGNATION_EPOCHS=80 SOLVE_MPI_MIN_REL_IMPROVEMENT=10 SOLVE_MPI_RANKS=$${SLURM_NTASKS:-4} SOLVE_MPI_OMP_THREADS=32 SOLVE_MPI_LAUNCHER=mpirun\n"
	@printf "  make solve_cuda SOLVE_CUDA_REPEATS=3 SOLVE_CUDA_RUNTIME_S=300 SOLVE_CUDA_STAGNATION_EPOCHS=80 SOLVE_CUDA_MIN_REL_IMPROVEMENT=10\n"
	@printf "  make generate_problems GEN_CLIENTS=500,1000,2000,4000,8000,16000,32000,64000\n"
	@printf "  make generate_problems_big\n"
	@printf "  make solve_pyvrp SOLVE_CLIENTS=1000,2000 SOLVE_PYVRP_RUNTIME_S=300\n"
	@printf "  make solve_seq   SOLVE_CLIENTS=1000,2000 SOLVE_SEQ_RUNTIME_S=300 SOLVE_SEQ_STAGNATION_EPOCHS=80 SOLVE_SEQ_MIN_REL_IMPROVEMENT=10 SOLVE_SEQ_REPEATS=3\n"
	@printf "  make solve_cuda  SOLVE_CLIENTS=1000,2000 SOLVE_CUDA_REPEATS=3 SOLVE_CUDA_RUNTIME_S=300 SOLVE_CUDA_STAGNATION_EPOCHS=80 SOLVE_CUDA_MIN_REL_IMPROVEMENT=10\n"
	@printf "  make solve_mpi   SOLVE_CLIENTS=4000,8000 SOLVE_MPI_RANKS=4 SOLVE_MPI_OMP_THREADS=8 SOLVE_MPI_RUNTIME_S=300 SOLVE_MPI_STAGNATION_EPOCHS=80 SOLVE_MPI_MIN_REL_IMPROVEMENT=10 SOLVE_MPI_REPEATS=3\n"
	@printf "  make solve_memory_growth_non_cuda SOLVE_MPI_RANKS=4 SOLVE_MPI_OMP_THREADS=8\n"
	@printf "  make exp_strong_openmp\n"
	@printf "  make exp_weak_openmp\n"
	@printf "  make exp_strong_mpi\n"
	@printf "  make exp_strong_hybrid\n"
	@printf "  make exp_weak_mpi\n"
	@printf "  make exp_weak_hybrid\n"
	@printf "  make exp_cuda_all\n"
	@printf "  make run_scaling_tests\n"
	@printf "  make exp_all\n"
	@printf "  make solve_all   SOLVE_CLIENTS=1000,2000\n\n"
	@printf "TARGET GENERAZIONE PROBLEMI:\n"
	@printf "  %-42s | %s\n" "generate_problems" "Genera istanze .vrp + manifest.csv + manifest_openmp_mpi.csv + manifest_cuda.csv"
	@printf "  %-42s | %s\n" "generate_problems_big" "Profilo istanze grandi non-CUDA (4k..32k)"
	@printf "  %-42s | %s\n\n" "generate_clean" "Rimuove istanze/manifest generati in GEN_INST_DIR"
	@printf "TARGET BUILD:\n"
	@printf "  %-42s | %s\n" "all" "Compila tutti i solver -> seq + MPI+OpenMP + CUDA"
	@printf "  %-42s | %s\n" "seq" "Compila solo il solver sequenziale -> aco_vrp_seq.out"
	@printf "  %-42s | %s\n" "openmp_mpi" "Compila il solver MPI+OpenMP -> aco_vrp_openmp_mpi.out"
	@printf "  %-42s | %s\n" "cuda" "Compila il solver CUDA -> aco_vrp_cuda.out"
	@printf "  %-42s | %s\n" "debug" "Ricompila con flag -DDEBUG"
	@printf "  %-42s | %s\n\n" "clean" "Pulisce binari, oggetti, coverage e artefatti CUDA intermedi"
	@printf "TARGET DOCUMENTAZIONE PDF:\n"
	@printf "  %-42s | %s\n" "pdfs" "Compila tutti i documenti LaTeX principali"
	@printf "  %-42s | %s\n\n" "clean_pdfs" "Rimuove i PDF generati e gli intermedi LaTeX"
	@printf "TARGET SOLVE DA MANIFEST (PRODUZIONE DATI):\n"
	@printf "  %-42s | %s\n" "solve_prepare" "Crea cartelle output e verifica esistenza manifest"
	@printf "  %-42s | %s\n" "solve_pyvrp" "Legge SOLVE_MANIFEST, risolve con PyVRP, salva CSV + route txt"
	@printf "  %-42s | %s\n" "solve_seq" "Legge SOLVE_MANIFEST, esegue solver sequenziale, salva CSV + route txt"
	@printf "  %-42s | %s\n" "solve_cuda" "Legge SOLVE_MANIFEST_CUDA, esegue solver CUDA, salva CSV + route txt"
	@printf "  %-42s | %s\n" "solve_mpi" "Legge SOLVE_MANIFEST_MPI, esegue solver MPI, salva CSV + route txt"
	@printf "  %-42s | %s\n" "solve_memory_growth_non_cuda" "Esegue seq+mpi con ripetizioni e CSV con max_rss_gb"
	@printf "  %-42s | %s\n\n" "solve_all" "Esegue in sequenza: solve_pyvrp, solve_seq, solve_cuda, solve_mpi"
	@printf "TARGET ESPERIMENTI SCALING:\n"
	@printf "  %-42s | %s\n" "exp_strong_openmp" "Strong scaling OpenMP: N fisso, ranks=1, thread variabili"
	@printf "  %-42s | %s\n" "exp_strong_openmp_n8000_m256" "Strong OpenMP specializzato: n=8000, m=256, thread 1..16"
	@printf "  %-42s | %s\n" "exp_weak_openmp" "Weak scaling OpenMP: coppie (threads,n) da EXP_WEAK_OPENMP_PAIRS"
	@printf "  %-42s | %s\n" "exp_strong_mpi" "Strong scaling MPI: N fisso, OMP fisso, ranks variabili"
	@printf "  %-42s | %s\n" "exp_strong_hybrid" "Strong scaling ibrido: N fisso, coppie (ranks,threads)"
	@printf "  %-42s | %s\n" "exp_weak_mpi" "Weak scaling MPI: coppie (ranks,n) da EXP_WEAK_MPI_PAIRS"
	@printf "  %-42s | %s\n" "exp_weak_hybrid" "Weak scaling ibrido: triple (ranks,threads,n) da EXP_WEAK_HYBRID_TRIPLETS"
	@printf "  %-42s | %s\n" "exp_cuda_scaling_input" "CUDA problem-size sweep su una GPU fissa"
	@printf "  %-42s | %s\n" "exp_cuda_scaling_ants" "Sweep legacy sul numero di formiche (non incluso in exp_cuda_all)"
	@printf "  %-42s | %s\n" "exp_seq_for_cuda" "Test sequenziale (non scaling) per confronto CUDA"
	@printf "  %-42s | %s\n" "exp_cuda_all" "Esegue solo il problem-size sweep CUDA a GPU fissa"
	@printf "  %-42s | %s\n" "exp_practical_cpu" "Campagna pratica completa lato CPU (skip CUDA), pronta per job batch"
	@printf "  %-42s | %s\n" "exp_practical_gpu" "Campagna pratica lato GPU (solo sezioni CUDA), pronta per job batch"
	@printf "  %-42s | %s\n\n" "exp_all" "Esegue in sequenza: exp_strong_openmp, exp_weak_openmp, exp_strong_mpi, exp_strong_hybrid, exp_weak_mpi, exp_weak_hybrid"
	@printf "VARIABILI PER solve_*:\n"
	@printf "  %-60s | %s\n" "RESULTS_ROOT=results" "Root unica risultati (solve)"
	@printf "  %-60s | %s\n" "SOLVE_OUT_DIR=$(RESULTS_ROOT)/solve_manifest" "Directory base output solve_*"
	@printf "  %-60s | %s\n" "SOLVE_CSV_DIR=$(SOLVE_OUT_DIR)/csv" "Directory CSV solve_*"
	@printf "  %-60s | %s\n" "SOLVE_SOLUTIONS_DIR=$(SOLVE_OUT_DIR)/solutions" "Directory route per backend"
	@printf "  %-60s | %s\n" "SOLVE_MANIFEST=.../manifest.csv" "Manifest usato da solve_pyvrp/solve_seq"
	@printf "  %-60s | %s\n" "SOLVE_MANIFEST_MPI=.../manifest_openmp_mpi.csv" "Manifest usato da solve_mpi"
	@printf "  %-60s | %s\n" "SOLVE_MANIFEST_CUDA=.../manifest_cuda.csv" "Manifest usato da solve_cuda"
	@printf "  %-60s | %s\n" "SOLVE_CLIENTS=1000,2000,4000" "Filtra per numero clienti n (colonna 4 del manifest)"
	@printf "  %-60s | %s\n" "SOLVE_LIMIT=5" "Limita alle prime N righe dopo i filtri (0 = tutte)"
	@printf "  %-60s | %s\n" "SOLVE_PYVRP_RUNTIME_S=10" "Budget tempo per istanza PyVRP (secondi)"
	@printf "  %-60s | %s\n" "SOLVE_SEQ_RUNTIME_S=300" "Budget massimo seq per run (secondi)"
	@printf "  %-60s | %s\n" "SOLVE_SEQ_RUNTIME=60" "Alias compatibile di SOLVE_SEQ_RUNTIME_S"
	@printf "  %-60s | %s\n" "SOLVE_SEQ_STAGNATION_EPOCHS=0" "Stop seq dopo N epoche senza miglioramento relativo significativo (0=off)"
	@printf "  %-60s | %s\n" "SOLVE_SEQ_MIN_REL_IMPROVEMENT=0.1" "Percentuale minima di miglioramento relativo per epoca (0.1 = 0.1%%)"
	@printf "  %-60s | %s\n" "SOLVE_SEQ_M=0" "Override m (formiche) per solve_seq; 0=usa manifest"
	@printf "  %-60s | %s\n" "SOLVE_SEQ_REPEATS=1" "Ripetizioni per istanza nel solve_seq"
	@printf "  %-60s | %s\n" "SOLVE_MPI_RUNTIME_S=300" "Budget massimo MPI+OpenMP per run (secondi)"
	@printf "  %-60s | %s\n" "SOLVE_MPI_STAGNATION_EPOCHS=0" "Stop MPI per stagnazione (0 usa il fallback backend di 100 epoche)"
	@printf "  %-60s | %s\n" "SOLVE_MPI_MIN_REL_IMPROVEMENT=0.1" "Percentuale minima di miglioramento relativo per epoca MPI (0.1 = 0.1%%)"
	@printf "  %-60s | %s\n" "SOLVE_MPI_REPEATS=1" "Ripetizioni per istanza nel solve_mpi"
	@printf "  %-60s | %s\n" "SOLVE_MPI_M=0" "Override formiche MPI (0=usa il manifest)"
	@printf "  %-60s | %s\n" "SOLVE_MPI_FIXED_EPOCHS=0" "Epoche fisse MPI per benchmark riproducibili"
	@printf "  %-60s | %s\n" "SOLVE_PYVRP_SEED=1234" "Seed PyVRP"
	@printf "  %-60s | %s\n" "SOLVE_MPI_RANKS=2" "Numero processi MPI per solve_mpi"
	@printf "  %-60s | %s\n" "SOLVE_MPI_OMP_THREADS=2" "Thread OpenMP per rank MPI"
	@printf "  %-60s | %s\n" "SOLVE_MPI_LAUNCHER=auto" "Launcher MPI: auto|mpirun|srun"
	@printf "  %-60s | %s\n" "SOLVE_CUDA_RUNTIME_S=300" "Budget massimo CUDA per run (secondi)"
	@printf "  %-60s | %s\n" "SOLVE_CUDA_STAGNATION_EPOCHS=0" "Stop CUDA dopo N epoche senza miglioramento (0=off)"
	@printf "  %-60s | %s\n" "SOLVE_CUDA_MIN_REL_IMPROVEMENT=0.1" "Soglia minima di miglioramento relativo CUDA"
	@printf "  %-60s | %s\n" "SOLVE_CUDA_M=0" "Override formiche CUDA (0=usa il manifest)"
	@printf "  %-60s | %s\n" "SOLVE_CUDA_REPEATS=1" "Ripetizioni per istanza nel solve_cuda"
	@printf "  %-60s | %s\n" "SOLVE_MEMORY_GROWTH_CLIENTS=4000,...,64000" "Taglie del test crescita memoria non-CUDA"
	@printf "  %-60s | %s\n\n" "SOLVE_MEMORY_GROWTH_REPEATS=3" "Ripetizioni del test crescita memoria non-CUDA"
	@printf "VARIABILI PER exp_*:\n"
	@printf "  %-60s | %s\n" "EXP_REPEATS=5" "Ripetizioni per ogni punto sperimentale"
	@printf "  %-60s | %s\n" "EXP_RUNTIME_S=300" "Limite di ogni run in secondi"
	@printf "  %-60s | %s\n" "EXP_STAGNATION_EPOCHS=500" "Stop epoche senza miglioramento (usato in exp_*)"
	@printf "  %-60s | %s\n" "EXP_MIN_REL_IMPROVEMENT=0.1" "Soglia miglioramento relativo percentuale (0.1 = 0.1%%, 10 = 10%%)"
	@printf "  %-60s | %s\n" "EXP_MPI_LAUNCHER=mpirun" "Launcher MPI usato dai target exp_*"
	@printf "  %-60s | %s\n" "EXP_MAX_CLUSTER_NODES=4" "Numero massimo nodi MPI da usare negli auto-scaling"
	@printf "  %-60s | %s\n" "EXP_MAX_CPUS_PER_TASK=32" "Massimo thread OpenMP per task"
	@printf "  %-60s | %s\n" "EXP_MAX_TOTAL_CORES=128" "Massimo asse x delle curve strong"
	@printf "  %-60s | %s\n" "EXP_WEAK_BASE_N_PER_WORKER=1000" "Base N per worker usata nelle modalita auto weak"
	@printf "  %-60s | %s\n" "EXP_STRONG_OPENMP_N=16000" "N fisso per strong OpenMP"
	@printf "  %-60s | %s\n" "EXP_STRONG_OPENMP_THREADS='1 2 4 8 16 32'" "Thread OpenMP da testare su un nodo"
	@printf "  %-60s | %s\n" "EXP_WEAK_OPENMP_PAIRS=auto" "Coppie threads N per weak OpenMP (auto -> N proporzionale ai thread)"
	@printf "  %-60s | %s\n" "EXP_STRONG_MPI_N=16000" "N fisso per strong MPI"
	@printf "  %-60s | %s\n" "EXP_STRONG_MPI_RANKS='1 2 4'" "Rank/nodi MPI da testare"
	@printf "  %-60s | %s\n" "EXP_STRONG_MPI_OMP_THREADS=32" "OMP fisso per strong MPI"
	@printf "  %-60s | %s\n" "EXP_STRONG_HYBRID_N=16000" "N fisso per strong ibrido MPI+OpenMP"
	@printf "  %-60s | %s\n" "EXP_STRONG_HYBRID_PAIRS='1 1 ... 4 32'" "Curva combinata da 1 a 128 core"
	@printf "  %-60s | %s\n" "EXP_WEAK_MPI_PAIRS='1 1000 2 2000 4 4000'" "Coppie rank N per weak scaling MPI"
	@printf "  %-60s | %s\n\n" "EXP_WEAK_MPI_OMP_THREADS=32" "OMP fisso per weak MPI"
	@printf "  %-60s | %s\n\n" "EXP_WEAK_HYBRID_TRIPLETS='1 32 1000 ... 4 32 4000'" "Triple rank thread N per weak ibrido"
	@printf "  %-60s | %s\n" "EXP_CUDA_CLIENTS_FUNCTIONAL=..." "Clienti per test sequenziale di confronto"
	@printf "  %-60s | %s\n" "EXP_CUDA_M_LIST='64 128 256'" "Valori m testati in exp_cuda_scaling_ants"
	@printf "  %-60s | %s\n" "EXP_CUDA_SCALING_M_FIXED=256" "m fisso per exp_cuda_scaling_input"
	@printf "  %-60s | %s\n" "EXP_CUDA_SCALING_CLIENTS=..." "Problem-size sweep CUDA su una GPU fissa"
	@printf "  %-60s | %s\n" "EXP_CUDA_REPEATS=1" "Ripetizioni per test CUDA"
	@printf "  %-60s | %s\n" "EXP_CUDA_RUNTIME_S=300" "Budget runtime CUDA (secondi)"
	@printf "  %-60s | %s\n" "EXP_CUDA_STAGNATION_EPOCHS=500" "Early-stop per stagnazione CUDA"
	@printf "  %-60s | %s\n" "EXP_CUDA_MIN_REL_IMPROVEMENT=10" "Soglia miglioramento relativa (percentuale)"
	@printf "VARIABILI GENERAZIONE:\n"
	@printf "  %-60s | %s\n" "GEN_INST_DIR=instances/generated_benchmark" "Directory dove scrivere .vrp e manifest"
	@printf "  %-60s | %s\n" "GEN_CLIENTS=500,1000,2000,4000,8000,16000,32000,64000" "Taglie n da generare (CSV separato da virgole)"
	@printf "  %-60s | %s\n" "GEN_SEED_BASE=19000" "Seed base; per ogni istanza incrementa di 1"
	@printf "  %-60s | %s\n" "GEN_GRID=100" "Griglia coordinate passata al generatore"
	@printf "  %-60s | %s\n" "GEN_SOLVER_SEED=1234" "Seed solver scritto nei manifest"
	@printf "  %-60s | %s\n" "GEN_TARGET_CUSTOMERS_PER_VEHICLE=1024" "Obiettivo medio clienti/veicolo: K = ceil(n / target)"
	@printf "  %-60s | %s\n" "GEN_MIN_VEHICLES=8" "Minimo veicoli generati"
	@printf "  %-60s | %s\n" "GEN_MAX_VEHICLES=512" "Massimo veicoli generati"
	@printf "  %-60s | %s\n" "GEN_CAPACITY_SLACK_PERCENT=20" "Slack percentuale sulla capacita: CAPACITY = ceil((1 + slack/100) * n / K)"
	@printf "  %-60s | %s\n" "GEN_CUDA_M=256" "Numero formiche fisso nel manifest CUDA generato"
	@printf "  %-60s | %s\n\n" "Capacita generata" "Sempre ceil((1 + slack/100) * n / K) con domanda unitaria per cliente"
	@printf "OUTPUT GENERATI DA solve_*:\n"
	@printf "  %-85s | %s\n" "$(SOLVE_CSV_DIR)/manifest_pyvrp_per_instance_results.csv" "CSV PyVRP con elapsed, memoria (max_rss_gb), costo"
	@printf "  %-85s | %s\n" "$(SOLVE_CSV_DIR)/manifest_seq_per_instance_results.csv" "CSV solver sequenziale (con max_rss_gb)"
	@printf "  %-85s | %s\n" "$(SOLVE_CSV_DIR)/manifest_cuda_per_instance_results.csv" "CSV solver CUDA"
	@printf "  %-85s | %s\n" "$(SOLVE_CSV_DIR)/manifest_openmp_mpi_per_instance_results.csv" "CSV solver MPI+OpenMP (con max_rss_gb)"
	@printf "  %-85s | %s\n\n" "$(SOLVE_SOLUTIONS_DIR)/<backend>/*.txt" "Route complete per ogni istanza/backend"
